### ISSUE TITLE
Add New Account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2228]
-Accounts are showing pre-selected.
![File (14)](https://user-images.githubusercontent.com/62699947/101592110-b5928480-3a13-11eb-9b6e-afac79466b04.jpg)

-Add new should be enabled.
![File (15)](https://user-images.githubusercontent.com/62699947/101592389-2c2f8200-3a14-11eb-9376-3465499ed0ea.jpg)

**Comment by AliMeer** [comment]
This is fixed in 179

**Comment by cakesoft-swati** [comment]
-Now the accounts are not showing pre-selected.
-But second issue "Add new should be enabled." is not resolved yet.

**Comment by CypherPoet** [comment]
I'm not able to replicate the "Add New" button not being enabled. Are there any steps to take to cause this?

**Comment by AliMeer** [comment]
@CypherPoet I think she the add a new account tile on the home screen that looks greyed out so appears to be disabled.

**Comment by CypherPoet** [comment]
Initially, I tried matching the opacity in the [latest design](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/e85c6b64-b24e-4350-a3f2-19a8244b78f2/specs/). 

I recently darkened the background a bit to make it look less "disabled", though:

![image](https://user-images.githubusercontent.com/46851636/101948218-45246880-3bb7-11eb-9d0e-6da74de26bb2.png)

**Comment by CypherPoet** [comment]
@AliMeer @antuz123 If that looks better, I'm thinking we could close this issue.

**Comment by antuz123** [comment]
Just look at the latest live app when donation account is not added @CypherPoet

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.4.0(182)
