### ISSUE TITLE
The text for new Donation account is overlaying on the icon.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2378]
![File (19)](https://user-images.githubusercontent.com/62699947/103127401-a66c3180-46b7-11eb-9431-4914d85eda73.jpg)

**Comment by CypherPoet** [comment]
This should have been fixed as part of #2427

**Comment by cakesoft-swati** [comment]
![tempFileForShare_20210111-144529](https://user-images.githubusercontent.com/62699947/104165393-4dbec780-541f-11eb-9529-b2753435b47e.jpg)
-Still having the same issuewhen entering the long description.
-Tested on Staging,dev app version 1.4.1(195)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(202)
