### ISSUE TITLE
UI issue when adding contacts from F&F.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2621]
-When we go to search contacts(Friends and Family> Add a contact >Search), then that search bar is going up so much that we cannot see it.[Tested on SAMSUNG Galaxy A50]

-On friends and Family >Add a contact : After selecting the contact, the Confirm and Proceed button is not visible, due to which we are unable to proceed[happening on both ios and android device].

**Comment by AliMeer** [comment]
The second part of the issue is fixed in build 215.

The first part about the search box going too high to be visible cannot be replicated in any device on Browser stack and not on any emulator that I could get I have tried 5 different emulators of varying sizes. Please retest it in 215.

**Comment by cakesoft-swati** [comment]
-The second part of the issue is verified in build 215.
-But the second part is still happening on Android device(SAMSUNG Galaxy A50)
-I tried some other devices on Browser stact but unaable to replicate this issue.
-I think it's only on this particaular device.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.2(216)
