### ISSUE TITLE
Mandatory Upgrade Notification with reminder

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3228]
Mandatory upgrade notification with option to ignore reminder limit is not working.

**Comment by cakesoft-devika** [comment]
Tested on Dev v1.4.6(235): 
For the third notification, I close the notification window instead of tap on the "Reminder Later" button, and then the app doesn't force for 1.5.1 update

**Comment by cakesoft-nikhita** [comment]
One Condition is missed on Login Page. Fixed now

**Comment by cakesoft-devika** [comment]
Tested on Dev v1.4.6(235) and It is still reproducible with the mentioned scenario in comment

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
