### ISSUE TITLE
Unhide accounts

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5007]
All accounts are not un-hidden. 

When I hide the accounts, only the accounts that did not change their names are un-hidden with the latest change. 

The accounts for which I had changed the names are still hidden. I had changed the name of the Checking Account and the Savings Account and created one more Savings Account with a different name.
![File (87)](https://user-images.githubusercontent.com/62699947/145008485-d4840003-94f2-41af-b032-a8eb8c26ec31.jpg)

**Comment by Parsh** [comment]
Might get resolved via: https://github.com/bithyve/hexa/pull/5015
We'll have to test it on the source device to confirm

**Comment by cakesoft-swati** [comment]
- Still not able to see hidden account from the old bug - need to write a migration script to forcefully show/ unhide/ un-archive specific accounts

**Comment by antuz123** [comment]
Force unhide and unarchive all accounts for now

**Comment by Parsh** [comment]
Note:
This could have happened due to the conflicts between changes like hiding the Test Account and the account reordering changes. We should look at the upgrade scripts we are using during these two changes

> What happens to the account shells which have flags as null? (Archive and Hide flag)

Configuration Log to assist w/ debugging
In the 70 release, we can add a button called “More details” inside the Wallet Version details screen which shows us - Account shells - their name - their visibility and archive flags

**Comment by Parsh** [comment]
Debug data is ready.

Waiting for #5370 @Raheel1258

**Comment by Parsh** [comment]
#5453 This doesn't actually fix the issue but provides debug logs for the account management screen, using which we'll be able to further investigate the above issue.

@cakesoft-swati What you need to check is that that the debug logs are showing up clearly when you triple tap on the Account management screen.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
